## Copyright (C) 1997-2018 Reyesoft <info@reyesoft.com>.
## This file is part of a Reyesoft Project. This can not be copied and/or
## distributed without the express permission of Reyesoft

image: reyesoft/php-mysql56

pipelines:
    default:
        - step:
            name: Install dependecies, CI lint and tests
            caches:
                - composer
            script:
                - composer install --no-interaction --no-progress
                - composer ci
                - composer ci-php-md
                - sh resources/ci/migrate.sh
                # - composer coverage
                - composer test
                - sh vendor/reyesoft/ci/db/laravel-reset.sh

# master is deployed via webhook
# git remote add production http://reyesoft@jsonapiplayground.reyesoft.com/plesk-git/jsonapiplayground.git
# git push production master:master
