## Copyright (C) 1997-2018 Reyesoft <info@reyesoft.com>.
## This file is part of a Reyesoft Project. This can not be copied and/or
## distributed without the express permission of Reyesoft

image: susa4ostec/bitbucket-pipelines-php7.1-mysql

pipelines:
    default:
        - step:
            name: Install dependecies and test
            caches:
                - composer
            script:
                - apt-get update -q
                - apt-get install php7.1-soap php7.1-zip --no-install-recommends -qq --yes
                - sh resources/bash/bitbucket-test.sh
    branches:
        master:
            - step:
                name: Install dependecies and test
                image: susa4ostec/bitbucket-pipelines-php7.1-mysql
                script:
                    - apt-get update -q
                    - apt-get install php7.1-soap php7.1-zip --no-install-recommends -qq --yes
                    - sh resources/bash/bitbucket-test.sh
                    - # run vía webhook
                    - # git remote add production http://reyesoft@jsonapiplayground.reyesoft.com/plesk-git/jsonapiplayground.git
                    - # git push production master:master
