#!/bin/sh

## Copyright (C) 1997-2017 Reyesoft <info@reyesoft.com>.
## This file is part of a Reyesoft Project. This can not be copied and/or
## distributed without the express permission of Reyesoft

# https://stackoverflow.com/questions/16483119/an-example-of-how-to-use-getopts-in-bash?answertab=votes#tab-top
while getopts ":f" o; do
    case "${o}" in
        f)
            f=1
            ;;
    esac
done

php artisan migrate:status --env=testing | grep -E '^\| N|^No migrations'    >> /dev/null
if [ "$?" -eq 0 ] || [ "${f}" ] ; then
    echo 'Migrations required. Lets do it!'

    php artisan config:clear
    php artisan migrate:refresh --seed --env=testing

    # ide helper
    php artisan migrate
    php artisan ide-helper:models --nowrite --filename=bootstrap/cache/_ide_helper_models.php
    php artisan ide-helper:meta --filename=bootstrap/cache/_ide_helper_meta.php
    php artisan ide-helper:generate bootstrap/cache/.phpstorm.meta.php
else
    echo 'Migrations are not required.'
fi;
phpunit
